-- AlterTable
ALTER TABLE "faucet_grants" ALTER COLUMN "lastGrantAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "feed_events" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "fixtures" ALTER COLUMN "kickoffTs" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "keeper_runs" ALTER COLUMN "startedAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "lastHeartbeat" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "lastEventAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "lastSettlementAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "kv" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "markets" ALTER COLUMN "lockTime" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "settledAt" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "odds_snapshots" ALTER COLUMN "takenAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "positions" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "receipts" ALTER COLUMN "settledAt" SET DATA TYPE TIMESTAMPTZ(3);
